# Generated by Django 4.1 on 2023-10-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contenttype_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='code',
            field=models.CharField(default='code', max_length=50, unique=True),
        ),
    ]
