# Generated by Django 4.1 on 2023-10-03 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
