# Generated by Django 4.1 on 2023-10-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_page_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttype',
            name='code',
            field=models.CharField(default='code', max_length=50, unique=True),
        ),
    ]
