# Generated by Django 4.1 on 2023-10-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contenttype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='theme',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
