# Generated by Django 4.1 on 2023-10-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_content_description_alter_content_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='content', max_length=50),
        ),
    ]
